[package]
name = "regex_ops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "regex_ops"
path = "src/main.rs"

[dependencies]
regex = "1.8.1"
